### ISSUE TITLE
Invoking Sort Lines raises exception in PyCharm

### ISSUE THREAD

**Issue by tunecrew** [krasa/StringManipulation#105]
**Describe the bug**
Invoking `Sort Lines` on selected text raises an exception intermittently.

**To Reproduce**
1. Select text to be sorted in PyCharm editor
2. Invoke `Sort Lines` via either `Edit` menu or assigned keyboard shortcut
3. Text is not sorted
4. Little red badge with exclamation point flashes in lower right corner of PyCharm
5. Clicking on it reveals window w/ "Exception in plugin String Manipulation"
6. Exception is:
```
java.lang.NumberFormatException: For input string: "from d"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:534)
	at osmedile.intellij.stringmanip.sort.support.Sort$9.toHex(Sort.java:103)
	at osmedile.intellij.stringmanip.sort.support.Sort$9.compare(Sort.java:94)
	at osmedile.intellij.stringmanip.sort.support.Sort$9.compare(Sort.java:91)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
	at osmedile.intellij.stringmanip.sort.support.Sort.sortLines(Sort.java:128)
	at osmedile.intellij.stringmanip.sort.support.SortLines.normalSort(SortLines.java:87)
	at osmedile.intellij.stringmanip.sort.support.SortLines.sortLines(SortLines.java:51)
	at osmedile.intellij.stringmanip.sort.support.SortTypeDialog.sort(SortTypeDialog.java:251)
	at osmedile.intellij.stringmanip.sort.support.SortTypeDialog.preview(SortTypeDialog.java:221)
	at osmedile.intellij.stringmanip.sort.support.SortTypeDialog.updateComponents(SortTypeDialog.java:94)
	at osmedile.intellij.stringmanip.sort.support.SortTypeDialog.<init>(SortTypeDialog.java:172)
	at osmedile.intellij.stringmanip.sort.SortAction.getSortSettings(SortAction.java:64)
	at osmedile.intellij.stringmanip.sort.SortAction$1.beforeWriteAction(SortAction.java:42)
	at osmedile.intellij.stringmanip.MyEditorWriteActionHandler.doExecute(MyEditorWriteActionHandler.java:30)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:88)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:197)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Expected behavior**
Text is sorted and no exception is raised.

**Environment :**
PyCharm Professional 2020.2
MacOS 10.15.6
Java 14.0.2
String Manipulation 8.3.191.000.3

**Additional context**
`from d` in exception is just the first few characters of the selected text. The same behaviour happens regardless of what is selected.

Bigger problem here is it works SOMETIMES

**Comment by krasa** [comment]
Do not select `Hexadecimal` sorting

**Comment by tunecrew** [comment]
> Do not select `Hexadecimal` sorting

I am not selecting Hexadecimal sorting. In fact, the window that lets you select the type of sort never even pops up.

**Comment by krasa** [comment]
Oh, I see. It was probably selected from the last time.
Thanks for the report!

Here's a fix:
[StringManipulation.zip](https://github.com/krasa/StringManipulation/files/5076144/StringManipulation.zip)

**Comment by tunecrew** [comment]
Thanks!
