### ISSUE TITLE
Unable to install the plug in IntelliJ 2022.1.1

### ISSUE THREAD

**Issue by obedsoto** [krasa/StringManipulation#180]
I am unable to install the plug in after upgrading IntelliJ to 2022.1.1

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.redhat.devtools.intellij.telemetry (0.0.2.18)
    org.jboss.tools.intellij.analytics (0.4.0.45)
    google-java-format (1.15.0.0)
    com.linsage (1.0.6)
    com.github.novotnyr.jwt-intellij-plugin (0.11)
    PlantUML integration (5.12.0)
    org.sonarlint.idea (6.7.0.45926)
    com.mallowigi (64.0.0)
    MavenRunHelper (4.20.213.3714.1)
    org.mapstruct.intellij (1.3.1)
    org.jfrog.idea (1.14.1)
    com.chrisrm.idea.MaterialThemeUI (7.5.0)

Kotlin: 221-1.6.21-release-337-IJ5591.52

===

I get the following error:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/22803310/170317877-414a9327-4041-4353-9c1a-52f768c271ca.png">

=== logs

2022-05-25 12:44:20,031 [  83525]   WARN - #c.i.i.p.PluginManager - Cannot load /var/folders/g7/l524dy057_3b6cv0rvlkzwrm0000gn/T/plugin9056057356266124392/StringManipulation/lib/StringManipulation.jar
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.intellij.ide.plugins.PluginXmlPathResolver$Companion.toLoadPath$intellij_platform_core_impl(PluginXmlPathResolver.kt:52)
	at com.intellij.ide.plugins.PluginXmlPathResolver.resolvePath(PluginXmlPathResolver.kt:115)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.processOldDependencies(IdeaPluginDescriptorImpl.kt:256)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.kt:218)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromJar(PluginDescriptorLoader.kt:152)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadFromPluginDir(PluginDescriptorLoader.kt:232)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromFileOrDir(PluginDescriptorLoader.kt:192)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromFileOrDir$default(PluginDescriptorLoader.kt:188)
	at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromArtifact(PluginDescriptorLoader.kt:541)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.loadDescriptorFromArtifact(PluginDownloader.java:269)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:235)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:257)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstallWithCallback(PluginInstallOperation.java:225)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:198)
	at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:138)
	at com.intellij.ide.plugins.newui.MyPluginModel.runInstallOperation(MyPluginModel.java:441)
	at com.intellij.ide.plugins.newui.MyPluginModel$1.run(MyPluginModel.java:409)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-05-25 12:44:20,036 [  83530]   INFO - #c.i.o.u.i.PluginDownloader - PluginDownloader error: Failed to load the plugin descriptor from the downloaded archive. The archive is probably not an IntelliJ plugin.

**Comment by krasa** [comment]
You can try this: [StringManipulation.zip](https://github.com/krasa/StringManipulation/files/8773653/StringManipulation.zip)

**Comment by obedsoto** [comment]
That worked! thank you.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/22803310/170361987-a7c3b1f2-3ee9-45a0-94b4-571733be3605.png">
