### ISSUE TITLE
Exception when running snapshot build of latest intellij-community master 

### ISSUE THREAD

**Issue by vsch** [krasa/StringManipulation#99]
**Describe the bug**
Exception report when **running snapshot build** of latest intellij-community master branch.

**To Reproduce**
1. Error occurs on startup of the IDE

**Expected behavior**
no exception

**Screenshots**
Exception stack trace:

```
java.lang.ClassCastException: class com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler cannot be cast to class osmedile.intellij.stringmanip.MyEditorWriteActionHandler (com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler is in unnamed module of loader com.intellij.ide.BootstrapClassLoaderUtil$TransformingLoader @1a8a8f7c; osmedile.intellij.stringmanip.MyEditorWriteActionHandler is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @51f6b457)
	at osmedile.intellij.stringmanip.styles.custom.CustomAction.<init>(CustomAction.java:27)
	at osmedile.intellij.stringmanip.styles.custom.CustomAction.<init>(CustomAction.java:16)
	at osmedile.intellij.stringmanip.ShortcutStartupActivity.registerAction(ShortcutStartupActivity.java:50)
	at osmedile.intellij.stringmanip.ShortcutStartupActivity.registerActions(ShortcutStartupActivity.java:44)
	at osmedile.intellij.stringmanip.ShortcutStartupActivity.runActivity(ShortcutStartupActivity.java:29)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:293)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:237)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:466)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:458)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:943)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Environment :**
```
IntelliJ IDEA 2020.2 Snapshot (Community Edition)
Build #IC-201.7223.91, built on May 2, 2020
Runtime version: 11.0.7+10-b903.3 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 6023M
Cores: 16
Registry: ide.ui.tree.indent=1, ide.mac.boldEditorTabs=true, show.diff.preview.as.editor.tab=true, gui.form.edit.property.keys=true, ide.popup.resizable.border.sensitivity=6, uast.java.use.psi.type.precheck=false, undo.documentUndoLimit=200, debugger.show.values.inplace=true, show.diff.as.editor.tab=true, ide.browser.jcef.enabled=true, undo.globalUndoLimit=50, debugger.watches.in.variables=false, vcs.commit.tool.window=false, debugger.single.smart.step.force=false, focus.fix.lost.cursor=true, debugger.valueTooltipAutoShowOnSelection=true, vcs.force.non.modal.commit=true, vcs.non.modal.commit.split.horizontal.if.no.diff.preview=true, editor.caret.width=1, ide.new.editor.tabs.selection.color=0,136,238
Non-Bundled Plugins: CMD Support, PlantUML integration, PsiViewer, String Manipulation, com.bulenkov.intellij.png.optimizer, YourKit Java Profiler 2019.8-b136 Integration, org.jetbrains.idea.grammar, com.intellij.marketplace, de.juserv.intellij-propertiessort, com.lid.intellij.translateme, com.ultrahob.zerolength.plugin, com.vladsch.MissingInActions, com.vladsch.PluginDevelopersToolbox, com.vladsch.plugins.consoleFileCaddy, com.vladsch.plugins.touchTypistsCompletionCaddy, org.intellij.RegexpTester, com.vladsch.git-file-case-fixer, mobi.hsz.idea.gitignore, nb-mind-map-idea, com.jetbrains.space, com.vladsch.idea.multimarkdown
```

**Additional context**
**running snapshot build** of latest intellij-community master branch.

**Comment by vsch** [comment]
Also occurs when another project is opened in the IDE.

**Comment by krasa** [comment]
Thanks! You can update.
